setwd("~/cirsium/environmental")
getwd()

library(ggplot2)
library(ggpubr)
library(phytools)
library(caper)
library(geiger)

tree = read.tree("cirsium.phyluce95p.ultrametric.tre")

#### tree mapping ####

X <- read.csv("cirsium_environmental_allcombined_DR.csv", row.names=1)
aridity<-setNames(X[,1],rownames(X))
BIO1<-setNames(X[,2],rownames(X))
BIO2<-setNames(X[,3],rownames(X))
BIO3<-setNames(X[,4],rownames(X))
BIO4<-setNames(X[,5],rownames(X))
BIO5<-setNames(X[,6],rownames(X))
BIO6<-setNames(X[,7],rownames(X))
BIO7<-setNames(X[,8],rownames(X))
BIO8<-setNames(X[,9],rownames(X))
BIO9<-setNames(X[,10],rownames(X))
BIO10<-setNames(X[,11],rownames(X))
BIO11<-setNames(X[,12],rownames(X))
BIO12<-setNames(X[,13],rownames(X))
BIO13<-setNames(X[,14],rownames(X))
BIO14<-setNames(X[,15],rownames(X))
BIO15<-setNames(X[,16],rownames(X))
BIO16<-setNames(X[,17],rownames(X))
BIO17<-setNames(X[,18],rownames(X))
BIO18<-setNames(X[,19],rownames(X))
BIO19<-setNames(X[,20],rownames(X))
aspect<-setNames(X[,21],rownames(X))
elevation<-setNames(X[,22],rownames(X))
slope<-setNames(X[,23],rownames(X))
bulk<-setNames(X[,24],rownames(X))
clay<-setNames(X[,25],rownames(X))
coarse<-setNames(X[,26],rownames(X))
nitrogen<-setNames(X[,27],rownames(X))
pH<-setNames(X[,28],rownames(X))
sand<-setNames(X[,29],rownames(X))
silt<-setNames(X[,30],rownames(X))
carbon<-setNames(X[,31],rownames(X))
needleleaf<-setNames(X[,32],rownames(X))
evergreen<-setNames(X[,33],rownames(X))
deciduous<-setNames(X[,34],rownames(X))
mixed_trees<-setNames(X[,35],rownames(X))
shrubs<-setNames(X[,36],rownames(X))
herbaceous<-setNames(X[,37],rownames(X))


pdf(file="env_map1.pdf", width = 18, height = 18)
par(mfrow = c(3,3))
plot(setMap(contMap(tree,aridity,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="aridity")
plot(setMap(contMap(tree,BIO1,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO1")
plot(setMap(contMap(tree,BIO2,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO2")
plot(setMap(contMap(tree,BIO3,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO3")
plot(setMap(contMap(tree,BIO4,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO4")
plot(setMap(contMap(tree,BIO5,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO5")
plot(setMap(contMap(tree,BIO6,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO6")
plot(setMap(contMap(tree,BIO7,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO7")
plot(setMap(contMap(tree,BIO8,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO8")
dev.off()

pdf(file="env_map2.pdf", width = 18, height = 18)
par(mfrow = c(3,3))
plot(setMap(contMap(tree,BIO9,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO9")
plot(setMap(contMap(tree,BIO10,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO10")
plot(setMap(contMap(tree,BIO11,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO11")
plot(setMap(contMap(tree,BIO12,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO12")
plot(setMap(contMap(tree,BIO13,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO13")
plot(setMap(contMap(tree,BIO14,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO14")
plot(setMap(contMap(tree,BIO15,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO15")
plot(setMap(contMap(tree,BIO16,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO16")
plot(setMap(contMap(tree,BIO17,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO17")
dev.off()

pdf(file="env_map3.pdf", width = 18, height = 18)
par(mfrow = c(3,3))
plot(setMap(contMap(tree,BIO18,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO18")
plot(setMap(contMap(tree,BIO19,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="BIO19")
plot(setMap(contMap(tree,aspect,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="aspect")
plot(setMap(contMap(tree,elevation,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="elevation")
plot(setMap(contMap(tree,slope,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="slope")
plot(setMap(contMap(tree,carbon,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="carbon")
plot(setMap(contMap(tree,silt,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="silt")
plot(setMap(contMap(tree,sand,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="sand")
plot(setMap(contMap(tree,pH,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="pH")
dev.off()

pdf(file="env_map.pdf", width = 18, height = 18)
par(mfrow = c(3,3))
plot(setMap(contMap(tree,nitrogen,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="nitrogen")
plot(setMap(contMap(tree,coarse,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="coarse")
plot(setMap(contMap(tree,clay,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="clay")
plot(setMap(contMap(tree,bulk,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="bulk")
plot(setMap(contMap(tree,herbaceous,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="herbaceous")
plot(setMap(contMap(tree,shrubs,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="shrubs")
plot(setMap(contMap(tree,mixed_trees,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="mixed_trees")
plot(setMap(contMap(tree,deciduous,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="deciduous")
plot(setMap(contMap(tree,evergreen,plot=FALSE), invert=TRUE),legend=0.7*max(nodeHeights(tree)),sig=2,fsize=c(0.7,0.9),leg.txt="evergreen")
dev.off()

##### linear models ####
##### DR vc Environment ####

DR = read.csv("tip_DR_cirsium.csv", row.names = 1)
DR<-setNames(DR[,1],rownames(DR))
dr <- as.numeric(dr)
aridity <- as.numeric(aridity)
BIO1<-as.numeric(BIO1)
BIO2<-as.numeric(BIO2)
BIO3<-as.numeric(BIO3)
BIO4<-as.numeric(BIO4)
BIO5<-as.numeric(BIO5)
BIO6<-as.numeric(BIO6)
BIO7<-as.numeric(BIO7)
BIO8<-as.numeric(BIO8)
BIO9<-as.numeric(BIO9)
BIO10<-as.numeric(BIO10)
BIO11<-as.numeric(BIO11)
BIO12<-as.numeric(BIO12)
BIO13<-as.numeric(BIO13)
BIO14<-as.numeric(BIO14)
BIO15<-as.numeric(BIO15)
BIO16<-as.numeric(BIO16)
BIO17<-as.numeric(BIO17)
BIO18<-as.numeric(BIO18)
BIO19<-as.numeric(BIO19)
aspect<-as.numeric(aspect)
elevation<-as.numeric(elevation)
slope<-as.numeric(slope)
carbon<-as.numeric(carbon)
silt<-as.numeric(silt)
sand<-as.numeric(sand)
pH<-as.numeric(pH)
nitrogen<-as.numeric(nitrogen)
coarse<-as.numeric(coarse)
clay<-as.numeric(clay)
bulk<-as.numeric(bulk)
herbaceous<-as.numeric(herbaceous)
shrubs<-as.numeric(shrubs)
mixed_trees<-as.numeric(mixed_trees)
deciduous<-as.numeric(deciduous)
evergreen<-as.numeric(evergreen)
DR<-as.numeric(DR)

#### linear models ####

aridity.lin <- (lm(formula = aridity ~ dr))
BIO1.lin<-(lm(formula = BIO1 ~ dr))
BIO2.lin<-(lm(formula = BIO2 ~ dr))
BIO3.lin<-(lm(formula = BIO3 ~ dr))
BIO4.lin<-(lm(formula = BIO4 ~ dr))
BIO5.lin<-(lm(formula = BIO5 ~ dr))
BIO6.lin<-(lm(formula = BIO6 ~ dr))
BIO7.lin<-(lm(formula = BIO7 ~ dr))
BIO8.lin<-(lm(formula = BIO8 ~ dr))
BIO9.lin<-(lm(formula = BIO9 ~ dr))
BIO10.lin<-(lm(formula = BIO10 ~ dr))
BIO11.lin<-(lm(formula = BIO11 ~ dr))
BIO12.lin<-(lm(formula = BIO12 ~ dr))
BIO13.lin<-(lm(formula = BIO13 ~ dr))
BIO14.lin<-(lm(formula = BIO14 ~ dr))
BIO15.lin<-(lm(formula = BIO15 ~ dr))
BIO16.lin<-(lm(formula = BIO16 ~ dr))
BIO17.lin<-(lm(formula = BIO17 ~ dr))
BIO18.lin<-(lm(formula = BIO18 ~ dr))
BIO19.lin<-(lm(formula = BIO19 ~ dr))
aspect.lin<-(lm(formula = aspect ~ dr))
elevation.lin<-(lm(formula = elevation ~ dr))
slope.lin<-(lm(formula = slope ~ dr))
carbon.lin<-(lm(formula = carbon ~ dr))
silt.lin<-(lm(formula = silt ~ dr))
sand.lin<-(lm(formula = sand ~ dr))
pH.lin<-(lm(formula = pH ~ dr))
nitrogen.lin<-(lm(formula = nitrogen ~ dr))
coarse.lin<-(lm(formula = coarse ~ dr))
clay.lin<-(lm(formula = clay ~ dr))
bulk.lin<-(lm(formula = bulk ~ dr))
herbaceous.lin<-(lm(formula = herbaceous ~ dr))
shrubs.lin<-(lm(formula = shrubs ~ dr))
mixed_trees.lin<-(lm(formula = mixed_trees ~ dr))
deciduous.lin<-(lm(formula = deciduous ~ dr))
evergreen.lin<-(lm(formula = evergreen ~ dr))


summary(aridity.lin)
summary(BIO1.lin)
summary(BIO2.lin)
summary(BIO3.lin)
summary(BIO4.lin)
summary(BIO5.lin)
summary(BIO6.lin)
summary(BIO7.lin)
summary(BIO8.lin)
summary(BIO9.lin)
summary(BIO10.lin)
summary(BIO11.lin)
summary(BIO12.lin)
summary(BIO13.lin)
summary(BIO14.lin)
summary(BIO15.lin)
summary(BIO16.lin)
summary(BIO17.lin)
summary(BIO18.lin)
summary(BIO19.lin)
summary(aspect.lin)
summary(elevation.lin)
summary(slope.lin)
summary(carbon.lin)
summary(silt.lin)
summary(sand.lin)
summary(pH.lin)
summary(nitrogen.lin)
summary(coarse.lin)
summary(clay.lin)
summary(bulk.lin)
summary(herbaceous.lin)
summary(shrubs.lin)
summary(mixed_trees.lin)
summary(deciduous.lin)
summary(evergreen.lin)

#### PGLS ####

X <- read.csv("cirsium_environmental_allcombined_DR.csv", row.names=1)
data <- data.frame(X)

data_object <- comparative.data(tree, data, Species, vcv=TRUE)

aridity.p <- pgls(formula = as.numeric(aridity) ~ DR, data = data_object)
BIO1.p <- pgls(formula = as.numeric(BIO1) ~ DR, data = data_object)
BIO2.p <- pgls(formula = as.numeric(BIO2) ~ DR, data = data_object)
BIO3.p <- pgls(formula = as.numeric(BIO3) ~ DR, data = data_object)
BIO4.p <- pgls(formula = as.numeric(BIO4) ~ DR, data = data_object)
BIO5.p <- pgls(formula = as.numeric(BIO5) ~ DR, data = data_object)
BIO6.p <- pgls(formula = as.numeric(BIO6) ~ DR, data = data_object)
BIO7.p <- pgls(formula = as.numeric(BIO7) ~ DR, data = data_object)
BIO8.p <- pgls(formula = as.numeric(BIO8) ~ DR, data = data_object)
BIO9.p <- pgls(formula = as.numeric(BIO9) ~ DR, data = data_object)
BIO10.p <- pgls(formula = as.numeric(BIO10) ~ DR, data = data_object)
BIO11.p <- pgls(formula = as.numeric(BIO11) ~ DR, data = data_object)
BIO12.p <- pgls(formula = as.numeric(BIO12) ~ DR, data = data_object)
BIO13.p <- pgls(formula = as.numeric(BIO13) ~ DR, data = data_object)
BIO14.p <- pgls(formula = as.numeric(BIO14) ~ DR, data = data_object)
BIO15.p <- pgls(formula = as.numeric(BIO15) ~ DR, data = data_object)
BIO16.p <- pgls(formula = as.numeric(BIO16) ~ DR, data = data_object)
BIO17.p <- pgls(formula = as.numeric(BIO17) ~ DR, data = data_object)
BIO18.p <- pgls(formula = as.numeric(BIO18) ~ DR, data = data_object)
BIO19.p <- pgls(formula = as.numeric(BIO19) ~ DR, data = data_object)
aspect.p <- pgls(formula = as.numeric(aspect) ~ DR, data = data_object)
elevation.p <- pgls(formula = as.numeric(elevation) ~ DR, data = data_object)
slope.p <- pgls(formula = as.numeric(slope) ~ DR, data = data_object)
bulk.p <- pgls(formula = as.numeric(bulk) ~ DR, data = data_object)
clay.p <- pgls(formula = as.numeric(clay) ~ DR, data = data_object)
coarse.p <- pgls(formula = as.numeric(coarse) ~ DR, data = data_object)
nitrogen.p <- pgls(formula = as.numeric(nitrogen) ~ DR, data = data_object)
ph.p <- pgls(formula = as.numeric(ph) ~ DR, data = data_object)
sand.p <- pgls(formula = as.numeric(sand) ~ DR, data = data_object)
silt.p <- pgls(formula = as.numeric(silt) ~ DR, data = data_object)
carbon.p <- pgls(formula = as.numeric(carbon) ~ DR, data = data_object)
needleleaf.p <- pgls(formula = as.numeric(needleleaf) ~ DR, data = data_object)
evergreen.p <- pgls(formula = as.numeric(evergreen) ~ DR, data = data_object)
deciduous.p <- pgls(formula = as.numeric(deciduous) ~ DR, data = data_object)
mixed_trees.p <- pgls(formula = as.numeric(mixed_trees) ~ DR, data = data_object)
shrubs.p <- pgls(formula = as.numeric(shrubs) ~ DR, data = data_object)
herbaceous.p <- pgls(formula = as.numeric(herbaceous) ~ DR, data = data_object)


summary(aridity.p)
summary(BIO1.p)
summary(BIO2.p)
summary(BIO3.p)
summary(BIO4.p)
summary(BIO5.p)
summary(BIO6.p)
summary(BIO7.p)
summary(BIO8.p)
summary(BIO9.p)
summary(BIO10.p)
summary(BIO11.p)
summary(BIO12.p)
summary(BIO13.p)
summary(BIO14.p)
summary(BIO15.p)
summary(BIO16.p)
summary(BIO17.p)
summary(BIO18.p)
summary(BIO19.p)
summary(aspect.p)
summary(elevation.p)
summary(slope.p)
summary(carbon.p)
summary(silt.p)
summary(sand.p)
summary(pH.p)
summary(nitrogen.p)
summary(coarse.p)
summary(clay.p)
summary(bulk.p)
summary(herbaceous.p)
summary(shrubs.p)
summary(mixed_trees.p)
summary(deciduous.p)
summary(evergreen.p)


