setwd("~/cirsium/traits/")
getwd()

library(ggplot2)
library(ggpubr)
library(phytools)
library(caper)
library(geiger)

tree = read.tree("cirsium.phyluce95p.ultrametric.tre")


##### linear models ####
##### pollination vc Environment ####

X <- read.csv("cirsium_environmental_allcombined_DR_pollinator.csv", row.names=1)

aridity<-as.numeric(setNames(X[,1],rownames(X)))
BIO1<-as.numeric(setNames(X[,2],rownames(X)))
BIO2<-as.numeric(setNames(X[,3],rownames(X)))
BIO3<-as.numeric(setNames(X[,4],rownames(X)))
BIO4<-as.numeric(setNames(X[,5],rownames(X)))
BIO5<-as.numeric(setNames(X[,6],rownames(X)))
BIO6<-as.numeric(setNames(X[,7],rownames(X)))
BIO7<-as.numeric(setNames(X[,8],rownames(X)))
BIO8<-as.numeric(setNames(X[,9],rownames(X)))
BIO9<-as.numeric(setNames(X[,10],rownames(X)))
BIO10<-as.numeric(setNames(X[,11],rownames(X)))
BIO11<-as.numeric(setNames(X[,12],rownames(X)))
BIO12<-as.numeric(setNames(X[,13],rownames(X)))
BIO13<-as.numeric(setNames(X[,14],rownames(X)))
BIO14<-as.numeric(setNames(X[,15],rownames(X)))
BIO15<-as.numeric(setNames(X[,16],rownames(X)))
BIO16<-as.numeric(setNames(X[,17],rownames(X)))
BIO17<-as.numeric(setNames(X[,18],rownames(X)))
BIO18<-as.numeric(setNames(X[,19],rownames(X)))
BIO19<-as.numeric(setNames(X[,20],rownames(X)))
aspect<-as.numeric(setNames(X[,21],rownames(X)))
elevation<-as.numeric(setNames(X[,22],rownames(X)))
slope<-as.numeric(setNames(X[,23],rownames(X)))
bulk<-as.numeric(setNames(X[,24],rownames(X)))
clay<-as.numeric(setNames(X[,25],rownames(X)))
coarse<-as.numeric(setNames(X[,26],rownames(X)))
nitrogen<-as.numeric(setNames(X[,27],rownames(X)))
pH<-as.numeric(setNames(X[,28],rownames(X)))
sand<-as.numeric(setNames(X[,29],rownames(X)))
silt<-as.numeric(setNames(X[,30],rownames(X)))
carbon<-as.numeric(setNames(X[,31],rownames(X)))
needleleaf<-as.numeric(setNames(X[,32],rownames(X)))
evergreen<-as.numeric(setNames(X[,33],rownames(X)))
deciduous<-as.numeric(setNames(X[,34],rownames(X)))
mixed_trees<-as.numeric(setNames(X[,35],rownames(X)))
shrubs<-as.numeric(setNames(X[,36],rownames(X)))
herbaceous<-as.numeric(setNames(X[,37],rownames(X)))
DR<-as.numeric(setNames(X[,38],rownames(X)))

poll<-as.factor(setNames(X[,39],rownames(X)))

#### linear models ####

aridity.lin <- (lm(formula = aridity ~ poll))
BIO1.lin<-(lm(formula = BIO1 ~ poll))
BIO2.lin<-(lm(formula = BIO2 ~ poll))
BIO3.lin<-(lm(formula = BIO3 ~ poll))
BIO4.lin<-(lm(formula = BIO4 ~ poll))
BIO5.lin<-(lm(formula = BIO5 ~ poll))
BIO6.lin<-(lm(formula = BIO6 ~ poll))
BIO7.lin<-(lm(formula = BIO7 ~ poll))
BIO8.lin<-(lm(formula = BIO8 ~ poll))
BIO9.lin<-(lm(formula = BIO9 ~ poll))
BIO10.lin<-(lm(formula = BIO10 ~ poll))
BIO11.lin<-(lm(formula = BIO11 ~ poll))
BIO12.lin<-(lm(formula = BIO12 ~ poll))
BIO13.lin<-(lm(formula = BIO13 ~ poll))
BIO14.lin<-(lm(formula = BIO14 ~ poll))
BIO15.lin<-(lm(formula = BIO15 ~ poll))
BIO16.lin<-(lm(formula = BIO16 ~ poll))
BIO17.lin<-(lm(formula = BIO17 ~ poll))
BIO18.lin<-(lm(formula = BIO18 ~ poll))
BIO19.lin<-(lm(formula = BIO19 ~ poll))
aspect.lin<-(lm(formula = aspect ~ poll))
elevation.lin<-(lm(formula = elevation ~ poll))
slope.lin<-(lm(formula = slope ~ poll))
carbon.lin<-(lm(formula = carbon ~ poll))
silt.lin<-(lm(formula = silt ~ poll))
sand.lin<-(lm(formula = sand ~ poll))
pH.lin<-(lm(formula = pH ~ poll))
nitrogen.lin<-(lm(formula = nitrogen ~ poll))
coarse.lin<-(lm(formula = coarse ~ poll))
clay.lin<-(lm(formula = clay ~ poll))
bulk.lin<-(lm(formula = bulk ~ poll))
herbaceous.lin<-(lm(formula = herbaceous ~ poll))
shrubs.lin<-(lm(formula = shrubs ~ poll))
mixed_trees.lin<-(lm(formula = mixed_trees ~ poll))
deciduous.lin<-(lm(formula = deciduous ~ poll))
evergreen.lin<-(lm(formula = evergreen ~ poll))
dr.lin<-(lm(formula = DR ~ poll))

summary(aridity.lin)
summary(BIO1.lin)
summary(BIO2.lin)
summary(BIO3.lin)
summary(BIO4.lin)
summary(BIO5.lin)
summary(BIO6.lin)
summary(BIO7.lin)
summary(BIO8.lin)
summary(BIO9.lin)
summary(BIO10.lin)
summary(BIO11.lin)
summary(BIO12.lin)
summary(BIO13.lin)
summary(BIO14.lin)
summary(BIO15.lin)
summary(BIO16.lin)
summary(BIO17.lin)
summary(BIO18.lin)
summary(BIO19.lin)
summary(aspect.lin)
summary(elevation.lin)
summary(slope.lin)
summary(carbon.lin)
summary(silt.lin)
summary(sand.lin)
summary(pH.lin)
summary(nitrogen.lin)
summary(coarse.lin)
summary(clay.lin)
summary(bulk.lin)
summary(herbaceous.lin)
summary(shrubs.lin)
summary(mixed_trees.lin)
summary(deciduous.lin)
summary(evergreen.lin)
summary(dr.lin)

####  PGLS ####

X <- read.csv("cirsium_environmental_allcombined_DR_pollinator.csv", row.names=1)
data <- data.frame(X)

data_object <- comparative.data(tree, data, Species, vcv=TRUE)

aridity.p <- pgls(formula = as.numeric(Aridity) ~ pollinator, data = data_object)
BIO1.p <- pgls(formula = as.numeric(BIO1) ~ pollinator, data = data_object)
BIO2.p <- pgls(formula = as.numeric(BIO2) ~ pollinator, data = data_object)
BIO3.p <- pgls(formula = as.numeric(BIO3) ~ pollinator, data = data_object)
BIO4.p <- pgls(formula = as.numeric(BIO4) ~ pollinator, data = data_object)
BIO5.p <- pgls(formula = as.numeric(BIO5) ~ pollinator, data = data_object)
BIO6.p <- pgls(formula = as.numeric(BIO6) ~ pollinator, data = data_object)
BIO7.p <- pgls(formula = as.numeric(BIO7) ~ pollinator, data = data_object)
BIO8.p <- pgls(formula = as.numeric(BIO8) ~ pollinator, data = data_object)
BIO9.p <- pgls(formula = as.numeric(BIO9) ~ pollinator, data = data_object)
BIO10.p <- pgls(formula = as.numeric(BIO10) ~ pollinator, data = data_object)
BIO11.p <- pgls(formula = as.numeric(BIO11) ~ pollinator, data = data_object)
BIO12.p <- pgls(formula = as.numeric(BIO12) ~ pollinator, data = data_object)
BIO13.p <- pgls(formula = as.numeric(BIO13) ~ pollinator, data = data_object)
BIO14.p <- pgls(formula = as.numeric(BIO14) ~ pollinator, data = data_object)
BIO15.p <- pgls(formula = as.numeric(BIO15) ~ pollinator, data = data_object)
BIO16.p <- pgls(formula = as.numeric(BIO16) ~ pollinator, data = data_object)
BIO17.p <- pgls(formula = as.numeric(BIO17) ~ pollinator, data = data_object)
BIO18.p <- pgls(formula = as.numeric(BIO18) ~ pollinator, data = data_object)
BIO19.p <- pgls(formula = as.numeric(BIO19) ~ pollinator, data = data_object)
aspect.p <- pgls(formula = as.numeric(Aspect) ~ pollinator, data = data_object)
elevation.p <- pgls(formula = as.numeric(Elevation) ~ pollinator, data = data_object)
slope.p <- pgls(formula = as.numeric(Slope) ~ pollinator, data = data_object)
bulk.p <- pgls(formula = as.numeric(Bulk) ~ pollinator, data = data_object)
clay.p <- pgls(formula = as.numeric(Clay) ~ pollinator, data = data_object)
coarse.p <- pgls(formula = as.numeric(Coarse) ~ pollinator, data = data_object)
nitrogen.p <- pgls(formula = as.numeric(Nitrogen) ~ pollinator, data = data_object)
ph.p <- pgls(formula = as.numeric(pH) ~ pollinator, data = data_object)
sand.p <- pgls(formula = as.numeric(Sand) ~ pollinator, data = data_object)
silt.p <- pgls(formula = as.numeric(Silt) ~ pollinator, data = data_object)
carbon.p <- pgls(formula = as.numeric(Carbon) ~ pollinator, data = data_object)
needleleaf.p <- pgls(formula = as.numeric(NeedleLeaf) ~ pollinator, data = data_object)
evergreen.p <- pgls(formula = as.numeric(Evergreen) ~ pollinator, data = data_object)
deciduous.p <- pgls(formula = as.numeric(Deciduous) ~ pollinator, data = data_object)
mixed_trees.p <- pgls(formula = as.numeric(Mixed) ~ pollinator, data = data_object)
shrubs.p <- pgls(formula = as.numeric(Shrubs) ~ pollinator, data = data_object)
herbaceous.p <- pgls(formula = as.numeric(Herbaceous) ~ pollinator, data = data_object)
DR.p <- pgls(formula = as.numeric(DR) ~ pollinator, data = data_object)

summary(aridity.p)
summary(BIO1.p)
summary(BIO2.p)
summary(BIO3.p)
summary(BIO4.p)
summary(BIO5.p)
summary(BIO6.p)
summary(BIO7.p)
summary(BIO8.p)
summary(BIO9.p)
summary(BIO10.p)
summary(BIO11.p)
summary(BIO12.p)
summary(BIO13.p)
summary(BIO14.p)
summary(BIO15.p)
summary(BIO16.p)
summary(BIO17.p)
summary(BIO18.p)
summary(BIO19.p)
summary(aspect.p)
summary(elevation.p)
summary(slope.p)
summary(carbon.p)
summary(silt.p)
summary(sand.p)
summary(pH.p)
summary(nitrogen.p)
summary(coarse.p)
summary(clay.p)
summary(bulk.p)
summary(herbaceous.p)
summary(shrubs.p)
summary(mixed_trees.p)
summary(deciduous.p)
summary(evergreen.p)
summary(DR.p)


##### violin plots ####

Y <- read.csv("cirsium_environmental_allcombined_DR_pollinator.csv")

Y <- data.frame(X)
Y$pollinator <- NULL

PL = read.csv("poll.csv", row.names = 1)
pollinator<-as.factor(setNames(PL[,1],rownames(PL)))

pdf(file="violin.DR.pdf", width = 3, height = 3)
ggplot(Y,aes(x=pollinator,y=DR,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$DR),(max(Y$DR)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
dev.off()

BIO1.plot<-ggplot(Y,aes(x=pollinator,y=BIO1,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO1),(max(Y$BIO1)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO2.plot<-ggplot(Y,aes(x=pollinator,y=BIO2,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO2),(max(Y$BIO2)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO3.plot<-ggplot(Y,aes(x=pollinator,y=BIO3,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO3),(max(Y$BIO3)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO4.plot<-ggplot(Y,aes(x=pollinator,y=BIO4,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO4),(max(Y$BIO4)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO5.plot<-ggplot(Y,aes(x=pollinator,y=BIO5,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO5),(max(Y$BIO5)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO6.plot<-ggplot(Y,aes(x=pollinator,y=BIO6,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO6),(max(Y$BIO6)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO7.plot<-ggplot(Y,aes(x=pollinator,y=BIO7,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO7),(max(Y$BIO7)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO8.plot<-ggplot(Y,aes(x=pollinator,y=BIO8,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO8),(max(Y$BIO8)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO9.plot<-ggplot(Y,aes(x=pollinator,y=BIO9,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO9),(max(Y$BIO9)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")

pdf(file="violin1.pdf", width = 18, height = 18)
ggarrange(BIO1.plot, BIO2.plot, BIO3.plot, BIO4.plot, BIO5.plot, BIO6.plot, BIO7.plot, BIO8.plot, BIO9.plot, 
          ncol = 3, nrow = 3)
dev.off()

BIO10.plot<-ggplot(Y,aes(x=pollinator,y=BIO10,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO10),(max(Y$BIO10)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO11.plot<-ggplot(Y,aes(x=pollinator,y=BIO11,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO11),(max(Y$BIO11)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO12.plot<-ggplot(Y,aes(x=pollinator,y=BIO12,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO12),(max(Y$BIO12)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO13.plot<-ggplot(Y,aes(x=pollinator,y=BIO13,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO13),(max(Y$BIO13)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO14.plot<-ggplot(Y,aes(x=pollinator,y=BIO14,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO14),(max(Y$BIO14)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO15.plot<-ggplot(Y,aes(x=pollinator,y=BIO15,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO15),(max(Y$BIO15)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO16.plot<-ggplot(Y,aes(x=pollinator,y=BIO16,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO16),(max(Y$BIO16)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO17.plot<-ggplot(Y,aes(x=pollinator,y=BIO17,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO17),(max(Y$BIO17)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
BIO18.plot<-ggplot(Y,aes(x=pollinator,y=BIO18,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO18),(max(Y$BIO18)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")

pdf(file="violin2.pdf", width = 18, height = 18)
ggarrange(BIO10.plot, BIO11.plot, BIO12.plot, BIO13.plot, BIO14.plot, BIO15.plot,
          BIO16.plot, BIO17.plot, BIO18.plot, ncol = 3, nrow = 3)
dev.off()

BIO19.plot<-ggplot(Y,aes(x=pollinator,y=BIO19,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$BIO19),(max(Y$BIO19)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Aspect.plot<-ggplot(Y,aes(x=pollinator,y=Aspect,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Aspect),(max(Y$Aspect)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Elevation.plot<-ggplot(Y,aes(x=pollinator,y=Elevation,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Elevation),(max(Y$Elevation)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Slope.plot<-ggplot(Y,aes(x=pollinator,y=Slope,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Slope),(max(Y$Slope)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Carbon.plot<-ggplot(Y,aes(x=pollinator,y=Carbon,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Carbon),(max(Y$Carbon)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Silt.plot<-ggplot(Y,aes(x=pollinator,y=Silt,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Silt),(max(Y$Silt)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Sand.plot<-ggplot(Y,aes(x=pollinator,y=Sand,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Sand),(max(Y$Sand)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
pH.plot<-ggplot(Y,aes(x=pollinator,y=pH,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$pH),(max(Y$pH)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Nitrogen.plot<-ggplot(Y,aes(x=pollinator,y=Nitrogen,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Nitrogen),(max(Y$Nitrogen)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")

pdf(file="violin3.pdf", width = 18, height = 18)
ggarrange(BIO19.plot, Aspect.plot, Elevation.plot, Slope.plot, Carbon.plot, Silt.plot, 
          Sand.plot, pH.plot, Nitrogen.plot, ncol = 3, nrow = 3)
dev.off()

Coarse.plot<-ggplot(Y,aes(x=pollinator,y=Coarse,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Coarse),(max(Y$Coarse)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Clay.plot<-ggplot(Y,aes(x=pollinator,y=Clay,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Clay),(max(Y$Clay)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Bulk.plot<-ggplot(Y,aes(x=pollinator,y=Bulk,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Bulk),(max(Y$Bulk)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Herbaceous.plot<-ggplot(Y,aes(x=pollinator,y=Herbaceous,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Herbaceous),(max(Y$Herbaceous)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Shrubs.plot<-ggplot(Y,aes(x=pollinator,y=Shrubs,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Shrubs),(max(Y$Shrubs)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Mixed.plot<-ggplot(Y,aes(x=pollinator,y=Mixed,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Mixed),(max(Y$Mixed)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Deciduous.plot<-ggplot(Y,aes(x=pollinator,y=Deciduous,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Deciduous),(max(Y$Deciduous)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Evergreen.plot<-ggplot(Y,aes(x=pollinator,y=Evergreen,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Evergreen),(max(Y$Evergreen)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")
Aridity.plot<-ggplot(Y,aes(x=pollinator,y=Aridity,fill=pollinator))+geom_violin(trim=TRUE)+ylim(min(Y$Aridity),(max(Y$Aridity)))+scale_fill_manual(values=c("#F1A340","#998EC3"))+theme(legend.position="none")

pdf(file="violin4.pdf", width = 18, height = 18)
ggarrange(Coarse.plot, Clay.plot, Bulk.plot, Herbaceous.plot, Shrubs.plot, Mixed.plot, Deciduous.plot, 
          Evergreen.plot, Aridity.plot, ncol = 3, nrow = 3)
dev.off()